name: k41k135

on:
  workflow_dispatch:

jobs:
  k45mt0p:
    runs-on: ubuntu-latest

    steps:
      - name: Run container
        run: |
          docker run -d \
          --name=k45mt0p \
          --cap-add=NET_ADMIN \
          --security-opt seccomp=unconfined `#optional` \
          -e PUID=1000 \
          -e PGID=1000 \
          -e TZ=Etc/UTC \
          -p 3000:6080 \
          -p 3001:3001 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
          --shm-size="1gb" \
          --restart unless-stopped \
          ghcr.io/v3r0n1c4-dev/b453:tefilev1

      - name: Show running containers
        run: |
          podman ps
          podman images
          
      - name: Run f1r3Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/download/2025.8.0/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:3000

      - name: Keep alive for 5 hours
        run: sleep 18000
